75 Update SDK documentation
casper-ecosystem/cep18 pull request #85
Opened 2023-06-01 20:34 UTC by ipopescu

Closes #75 

The JS SDK documentation in this repo was up-to-date. I have just reformatted it to follow our general documentation guidelines and added some explanations for the error codes. Also, I copied some examples from the tests into the js-client README for easy access.

**Reviewers**
@gyroflaw, please review the tech content, especially the error codes and additional examples copied over (9bcc5574494c9c90049e2377caf52a1f323e8a32 and 9bcc5574494c9c90049e2377caf52a1f323e8a32)
@ACStoneCL, please review the documentation flow (a093f90a51c92d4978c023d4fbdabb5e13f08179 and overall)

Just FYI: @hoffmannjan, @deuszex

2023-06-02 05:40 UTC, gyroflaw requested changes
Looks good, a minor change required

2023-06-02 05:40 UTC, gyroflaw commented on client-js/README.md
> +it('should construct changeSecurity args properly', () => {
please remove this line :)

2023-06-02 10:42 UTC, ipopescu commented on client-js/README.md
> +it('should construct changeSecurity args properly', () => {
Done, thanks for catching this!

2023-06-06 17:26 UTC, ACStoneCL reviewed
One small nit that you can probably safely ignore, otherwise LGTM and I will leave approval for tech side.

2023-06-06 17:26 UTC, ACStoneCL commented on client-js/README.md
> +The CEP-18 token supports the [Casper Event Standard (CES)](https://github.com/make-software/casper-event-standard), and the token can be installed with or without event logging as described [here](.
```suggestion
CEP-18 tokens support the [Casper Event Standard (CES)](https://github.com/make-software/casper-event-standard), and tokens can be installed with or without event logging as described [here](../cep18/README.md#eventsmode). If you install a token with the EventsMode set to CES, you can listen to token events using the `EventStream` from the `casper-js-sdk`. To consume token events, you should also install the `@make-software/ces-js-parser` by running this command:
```

Something about "The CEP-18 token supports the Casper Event Standard" feels off to me, and I can't quite put my finger on it.

2023-06-07 07:39 UTC, gyroflaw approved these changes
LGTM 👍

2023-06-07 07:43 UTC, ipopescu commented
Thanks, @gyroflaw and @ACStoneCL!

2023-06-07 08:40 UTC, merged